const myData = {
   login: "cswebdev",
   id: 118695281,
   node_id: "U_kgDOBxMlcQ",
   avatar_url: "https://avatars.githubusercontent.com/u/118695281?v=4",
   gravatar_id: "",
   url: "https://api.github.com/users/cswebdev",
   html_url: "https://github.com/cswebdev",
   followers_url: "https://api.github.com/users/cswebdev/followers",
   following_url:
      "https://api.github.com/users/cswebdev/following{/other_user}",
   gists_url: "https://api.github.com/users/cswebdev/gists{/gist_id}",
   starred_url: "https://api.github.com/users/cswebdev/starred{/owner}{/repo}",
   subscriptions_url: "https://api.github.com/users/cswebdev/subscriptions",
   organizations_url: "https://api.github.com/users/cswebdev/orgs",
   repos_url: "https://api.github.com/users/cswebdev/repos",
   events_url: "https://api.github.com/users/cswebdev/events{/privacy}",
   received_events_url: "https://api.github.com/users/cswebdev/received_events",
   type: "User",
   site_admin: false,
   name: "Chelsea S.",
   company: null,
   blog: "",
   location: null,
   email: null,
   hireable: null,
   bio: null,
   twitter_username: null,
   public_repos: 16,
   public_gists: 0,
   followers: 3,
   following: 9,
   created_at: "2022-11-20T22:20:41Z",
   updated_at: "2023-01-19T21:20:36Z",
};

export default myData;
